services:
  auth-generator:
    image: andrianovartemii/gm-test-task-auth-generator:latest
    ports:
      - "8082:8080"
    environment:
      AUTH_TOKEN_LIFETIME: 2
  gateway:
    build:
      context: ..
      dockerfile: ./deployments/gateway-dockerfile
    ports:
      - 8081:8080
    links:
     - redis
    environment:
      APP_NAME: "gateway-service"
      APP_VERSION: "0.1.0"
      HTTP_PORT: "8080"
      REDIS_CHANNEL: "tasks"
      REDIS_ADDRESS: "redis:6379"
      AUTH_URL: "auth-generator:8080"
      GRPC_PORT: "8080"
      GRPC_ADDRESS: "storage"
  storage:
    build:
      context: ..
      dockerfile: ./deployments/storage-dockerfile
    ports:
      - 8085:8080
    links:
     - redis
     - db
    environment:
      APP_NAME: "storage-service"
      APP_VERSION: "0.1.0"
      REDIS_CHANNEL: "tasks"
      REDIS_ADDRESS: "redis:6379"
      PG_URL: "postgres://app:passpasspass@db:5432/retailers"
      GRPC_PORT: "8080"

  db:
    image: postgres:15
    volumes:
      - db_data:/var/lib/postgresql
    restart: always
    environment:
      POSTGRES_DB: "retailers"
      POSTGRES_USER: "app"
      POSTGRES_PASSWORD: "passpasspass"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.2
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
volumes:
  db_data:
